version: '3.8'

services:
  producer:
    env_file:
      - .env
    command: ['npx', 'nodemon', '--config', 'nodemon-producer.json']
    volumes:
      - .:/app
      - producer_node_modules:/app/node_modules

  consumer:
    env_file:
      - .env
    command: ['npx', 'nodemon', '--config', 'nodemon-consumer.json']
    volumes:
      - .:/app
      - consumer_node_modules:/app/node_modules

volumes:
  producer_node_modules:
  consumer_node_modules:
