version: '3.8'

services:
  producer:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command: ['node', 'dist/producer/index.js'] # Producer-specific entry point
    depends_on:
      - mongo
      - rabbitmq
    ports:
      - '3001:3000'

  consumer:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - mongo
      - rabbitmq
    command: ['node', 'dist/consumer/index.js']
    ports:
      - '3002:3000'

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - '27017:27017'
    restart: always
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    ports:
      - '5672:5672' # RabbitMQ broker port
      - '15672:15672' # Management UI port
    env_file:
      - .env

volumes:
  mongo_data:
