version: '3.8'

services:
  producer:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command: ['node', 'dist/producer/index.js'] # Producer-specific entry point
    depends_on:
      - mongo
    ports:
      - '3001:3000'

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - '27017:27017'
    restart: always
